FROM golang:1.22 as builder
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o grpc-notify-server main.go
FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/grpc-notify-server .
COPY --from=builder /app/config/config.yml ./config/
EXPOSE 50051
CMD ["./grpc-notify-server"]
